variable "aws_region" {
  type        = string
  default     = "us-east-1"
  description = "AWS region for all resources."
}

variable "github_repository" {
  type        = string
  default     = "joshlebed/workshop"
  description = "GitHub repo (owner/name). Used to scope the GH Actions OIDC trust policy."
}

variable "budget_email_recipient" {
  type        = string
  default     = "joshlebed@gmail.com"
  description = "Email to receive the $5 monthly AWS budget alert. Routed through SNS, not SES."
}

variable "database_url" {
  type        = string
  sensitive   = true
  description = "Full Postgres connection string (Neon). Must include sslmode=require. Set in terraform.tfvars; never committed."
}

variable "apple_bundle_id" {
  type        = string
  default     = ""
  description = "Apple iOS bundle ID(s) — the accepted `aud` values for native Sign in with Apple tokens. Comma-separated list; one entry per client app (e.g. \"dev.josh.workshop,live.highscore.app\"). A single value with no comma behaves exactly as before. Empty string is allowed so `terraform apply` works before portal config; backend rejects verification until this is set."
}

variable "apple_services_id" {
  type        = string
  default     = ""
  description = "Apple Services ID(s) — the accepted `aud` values for web Sign in with Apple tokens. Comma-separated list; one entry per web surface. Configured in the Apple Developer portal; paste the identifier(s) here."
}

variable "google_ios_client_id" {
  type        = string
  default     = ""
  description = "Google OAuth iOS client ID(s) — the accepted `aud` values on native Google sign-in tokens. Comma-separated list; one entry per iOS client app."
}

variable "google_web_client_id" {
  type        = string
  default     = ""
  description = "Google OAuth web client ID(s) — the accepted `aud` values on web Google sign-in tokens. Comma-separated list; a single web client shared by several origins stays one entry."
}

variable "tmdb_api_key" {
  type        = string
  default     = ""
  sensitive   = true
  description = "TMDB API key for movie/TV search enrichment (Phase 2). Empty default lets infra apply before the key is obtained."
}

variable "google_books_api_key" {
  type        = string
  default     = ""
  sensitive   = true
  description = "Google Books API key for book search enrichment (Phase 2). Empty default lets infra apply before the key is obtained."
}

variable "apple_team_id" {
  type        = string
  default     = ""
  description = "Apple Developer Team ID (10 chars). With apple_key_id + apple_private_key, lets the backend exchange a Sign in with Apple authorization code for a refresh token and revoke it on account deletion (App Store Review Guideline 5.1.1(v)). Empty default keeps revocation reported as 'unavailable' instead of pretending it happened."
}

variable "apple_key_id" {
  type        = string
  default     = ""
  description = "Key ID of the Sign in with Apple private key (.p8) created at https://developer.apple.com/account/resources/authkeys/list."
}

variable "apple_private_key" {
  type        = string
  default     = ""
  sensitive   = true
  description = "Contents of the Sign in with Apple .p8 private key. Newlines may be escaped as \n. Set via `aws ssm put-parameter --overwrite` (the SSM param has ignore_changes), never committed."
}

variable "spotify_client_id" {
  type        = string
  default     = ""
  description = "Spotify Web API client ID. Register an app at https://developer.spotify.com/dashboard. Empty default lets infra apply before the app is registered."
}

variable "spotify_client_secret" {
  type        = string
  default     = ""
  sensitive   = true
  description = "Spotify Web API client secret. Used by the Album Shelf feature's Client Credentials flow to read public playlists."
}

variable "discord_notify_webhook_url" {
  type        = string
  default     = ""
  sensitive   = true
  description = "Discord webhook URL for operator notifications (new signups, new lists). Empty default lets infra apply before the webhook is created; the SSM param has ignore_changes so ops rotates via `aws ssm put-parameter --overwrite` without TF drift."
}

variable "niteshift_aws_account_id" {
  type        = string
  default     = "283250832593"
  description = "Niteshift's AWS account ID — the principal in the niteshift role's trust policy. Single value per niteshift install; only override if niteshift changes accounts."
}

variable "niteshift_external_id" {
  type        = string
  sensitive   = true
  description = "Per-repo External ID generated by Niteshift (Settings → Repositories → workshop → AWS tab). Conditions the assume-role call so other niteshift customers can't pivot in. Rotate via the niteshift UI if leaked."
}
