-- GENERATED by scripts/generate-game-code-seed.ts from src/lib/gameCode/builtin.ts
-- and specCode.ts. Do not edit by hand: seed.test.ts compares this file to the
-- generator's output.
--
-- Installs each game's parse / format code (the JavaScript the QuickJS sandbox
-- runs — see src/lib/gameCode/README.md) and records it as version 1 in
-- game_code_revisions. Idempotent: every statement skips rows that already
-- have code. Nothing reads these columns until GAME_CODE_PARSING is on.
-- Anthropeum
UPDATE "games"
SET "parse_code" = $gc$// "1,000" → 1000. Throws rather than guessing.
function toNumber(text) {
  const digits = text.replace(/,/g, "");
  const n = Number(digits);
  if (digits === "" || !Number.isFinite(n)) throw new Error("not a number: " + text);
  return n;
}

// "62,090 · top 38% of players today!" → 62090. The header's "·"
// ("Anthropeum.com · Jun 14 2026") has no digits in front of it.
function parse(raw) {
  const m = raw.match(/([\d,]+(?:\.\d+)?)\s*·/);
  if (!m) throw new Error("no points before a ·");
  return toNumber(m[1]);
}
$gc$,
    "format_code" = $gc$function nonEmptyLines(text) {
  return text.split(/\r?\n/).map((l) => l.trim()).filter((l) => l.length > 0);
}

// Drop the "Anthropeum.com · <date>" header and the "· top N% of players
// today!" brag; join the emoji grid and the bare score on one line.
function format(raw) {
  const lines = nonEmptyLines(raw)
    .filter((l) => !/anthropeum\.com/i.test(l))
    .map((l) => l.replace(/\s*·.*$/, "").trim());
  return lines.length ? lines.join(" ") : null;
}
$gc$,
    "code_version" = 1
WHERE "code_version" = 0 AND "game_key" = 'anthropeum';
--> statement-breakpoint
-- MapTap
UPDATE "games"
SET "parse_code" = $gc$// "Final score: 970" → 970
function parse(raw) {
  const m = raw.match(/Final score:\s*(\d+)/i);
  if (!m) throw new Error("no Final score line");
  return Number(m[1]);
}
$gc$,
    "format_code" = $gc$function stripUrls(text) {
  return text.replace(/\bhttps?:\/\/\S+/gi, "");
}

function nonEmptyLines(text) {
  return text.split(/\r?\n/).map((l) => l.trim()).filter((l) => l.length > 0);
}

// Drop the "www.maptap.gg <date>" header; keep the per-round line and the
// Final score line.
function format(raw) {
  const lines = nonEmptyLines(stripUrls(raw)).filter((l) => !/^(?:www\.)?maptap\.gg\b/i.test(l));
  return lines.length ? lines.join("\n") : null;
}
$gc$,
    "code_version" = 1
WHERE "code_version" = 0 AND "game_key" = 'maptap';
--> statement-breakpoint
-- Daily Tens
UPDATE "games"
SET "parse_code" = $gc$// A 5x2 grid of 🏆 (right) / ❌ (wrong); the score is the number of 🏆. An
// all-❌ day is a real 0. A share with no grid at all (just the ?ref= link)
// is not a result.
function parse(raw) {
  if (!/[🏆❌]/u.test(raw)) throw new Error("no 🏆/❌ grid");
  return raw.split("🏆").length - 1;
}
$gc$,
    "format_code" = $gc$// Turn the 5-row x 2-column grid on its side: the left column becomes the
// first row, the right column the second. Anything but a clean rectangle
// defers to the cleaned raw text.
function format(raw) {
  const rows = raw
    .split(/\r?\n/)
    .map((l) => l.replace(/\bhttps?:\/\/\S+/gi, "").match(/[🏆❌]/gu) || [])
    .filter((cells) => cells.length > 0);
  if (rows.length === 0) return null;
  const width = rows[0].length;
  if (rows.some((r) => r.length !== width)) return null;
  const out = [];
  for (let c = 0; c < width; c++) out.push(rows.map((r) => r[c]).join(""));
  return out.join("\n");
}
$gc$,
    "code_version" = 1
WHERE "code_version" = 0 AND "game_key" = 'dailytens';
--> statement-breakpoint
-- Satle
UPDATE "games"
SET "parse_code" = $gc$// "🛰Satle #449 5/6" → 5; "X/6" is a loss.
function parse(raw) {
  const m = raw.match(/Satle\s*#\d+\s+(\d+|X)\/6/i);
  if (!m) throw new Error("no Satle result line");
  return m[1].toUpperCase() === "X" ? null : Number(m[1]);
}
$gc$,
    "format_code" = $gc$function stripUrls(text) {
  return text.replace(/\bhttps?:\/\/\S+/gi, "");
}

function nonEmptyLines(text) {
  return text.split(/\r?\n/).map((l) => l.trim()).filter((l) => l.length > 0);
}

// A line of emoji / box characters only, with an optional "= N" tail (and
// whatever a player typed after it, e.g. "= 13(cheated)").
function isGridOnlyLine(line) {
  return !/[A-Za-z0-9]/.test(line.replace(/=\s*\d+.*$/, ""));
}

// "🛰Satle #468 6/6" + grid → "<grid> 6/6"
function format(raw) {
  const lines = nonEmptyLines(stripUrls(raw));
  const header = lines.find((l) => /satle/i.test(l));
  const grid = lines.find((l) => isGridOnlyLine(l) && !/satle/i.test(l));
  const fraction = header ? (header.match(/(\d+|X)\/\d+/i) || [])[0] : undefined;
  if (!grid || !fraction) return null;
  return grid + " " + fraction;
}
$gc$,
    "code_version" = 1
WHERE "code_version" = 0 AND "game_key" = 'satle';
--> statement-breakpoint
-- Travle
UPDATE "games"
SET "parse_code" = $gc$// "#travle #1250 +0" → 0 (extra guesses; lower is better).
// "#travle #1250 (9 away)" is a loss.
function parse(raw) {
  const m = raw.match(/#travle\s+#?\d+\s+\+(\d+)/i);
  if (m) return Number(m[1]);
  if (/#travle\s+#?\d+\s+\(\d+\s+away\)/i.test(raw)) return null;
  throw new Error("no #travle result line");
}
$gc$,
    "format_code" = $gc$function stripUrls(text) {
  return text.replace(/\bhttps?:\/\/\S+/gi, "");
}

function nonEmptyLines(text) {
  return text.split(/\r?\n/).map((l) => l.trim()).filter((l) => l.length > 0);
}

// A line of emoji / box characters only, with an optional "= N" tail (and
// whatever a player typed after it, e.g. "= 13(cheated)").
function isGridOnlyLine(line) {
  return !/[A-Za-z0-9]/.test(line.replace(/=\s*\d+.*$/, ""));
}

// "#travle #1260 +2" + grid → "<grid> +2" (keeps "(Perfect)" / "(2 hints)")
function format(raw) {
  const lines = nonEmptyLines(stripUrls(raw));
  const header = lines.find((l) => /travle/i.test(l));
  const grid = lines.find((l) => isGridOnlyLine(l) && !/travle/i.test(l));
  const score = header ? (header.match(/[+-]\d+(?:\s*\([^)]+\))?/) || [])[0] : undefined;
  if (!grid || !score) return null;
  return grid + " " + score;
}
$gc$,
    "code_version" = 1
WHERE "code_version" = 0 AND "game_key" = 'travle';
--> statement-breakpoint
-- Globle
UPDATE "games"
SET "parse_code" = $gc$// "⬜⬜🟧🟥🟩 = 5" → 5 (guesses; lower is better). The share has one "=".
function parse(raw) {
  const m = raw.match(/=\s*(\d+)/);
  if (!m) throw new Error("no '= N' guess count");
  return Number(m[1]);
}
$gc$,
    "format_code" = $gc$function stripUrls(text) {
  return text.replace(/\bhttps?:\/\/\S+/gi, "");
}

function nonEmptyLines(text) {
  return text.split(/\r?\n/).map((l) => l.trim()).filter((l) => l.length > 0);
}

// A line of emoji / box characters only, with an optional "= N" tail (and
// whatever a player typed after it, e.g. "= 13(cheated)").
function isGridOnlyLine(line) {
  return !/[A-Za-z0-9]/.test(line.replace(/=\s*\d+.*$/, ""));
}

// Keep the grid lines up to the one ending "= N" (long runs wrap); drop the
// date / streak header and the trailing hashtag.
function format(raw) {
  const lines = nonEmptyLines(stripUrls(raw));
  const start = lines.findIndex(isGridOnlyLine);
  if (start === -1) return null;
  const end = lines.findIndex((l, i) => i >= start && /=\s*\d+.*$/.test(l));
  if (end === -1) return null;
  return lines.slice(start, end + 1).join("\n");
}
$gc$,
    "code_version" = 1
WHERE "code_version" = 0 AND "game_key" = 'globle';
--> statement-breakpoint
-- Worldle
UPDATE "games"
SET "parse_code" = $gc$// "#Worldle #1287 (27.08.2026) 4/6 (100%)" → 4; "X/6" is a loss. The date is optional.
function parse(raw) {
  const m = raw.match(/Worldle\s*#?\d+\s+(?:\([\d.\/-]+\)\s+)?(\d+|X)\/6/i);
  if (!m) throw new Error("no Worldle result line");
  return m[1].toUpperCase() === "X" ? null : Number(m[1]);
}
$gc$,
    "format_code" = $gc$function stripUrls(text) {
  return text.replace(/\bhttps?:\/\/\S+/gi, "");
}

function nonEmptyLines(text) {
  return text.split(/\r?\n/).map((l) => l.trim()).filter((l) => l.length > 0);
}

// A line of emoji / box characters only, with an optional "= N" tail (and
// whatever a player typed after it, e.g. "= 13(cheated)").
function isGridOnlyLine(line) {
  return !/[A-Za-z0-9]/.test(line.replace(/=\s*\d+.*$/, ""));
}

// Collapse a Wordle-style grid to its 🟩 count per guess, plus the N/6 (or X/6)
// from the header: six rows become "🟩 2·3·4·4·4·5 6/6".
function greensSparkline(raw, headerPattern) {
  const lines = nonEmptyLines(stripUrls(raw));
  const greens = lines
    .filter((l) => isGridOnlyLine(l) && /[🟩🟨🟧🟥⬜⬛]/u.test(l))
    .map((l) => (l.match(/🟩/gu) || []).length);
  if (greens.length === 0) return null;
  const header = lines.find((l) => headerPattern.test(l));
  const fraction = header ? (header.match(/(?:\d+|X)\/\d+/i) || [])[0] : undefined;
  const sparkline = "🟩 " + greens.join("·");
  return fraction ? sparkline + " " + fraction : sparkline;
}

function format(raw) {
  return greensSparkline(raw, /worldle/i);
}
$gc$,
    "code_version" = 1
WHERE "code_version" = 0 AND "game_key" = 'worldle';
--> statement-breakpoint
-- Tradle
UPDATE "games"
SET "parse_code" = $gc$// "#Tradle #1547 1/6" → 1; "X/6" is a loss.
function parse(raw) {
  const m = raw.match(/Tradle\s*#?\d+\s+(\d+|X)\/6/i);
  if (!m) throw new Error("no Tradle result line");
  return m[1].toUpperCase() === "X" ? null : Number(m[1]);
}
$gc$,
    "format_code" = $gc$function stripUrls(text) {
  return text.replace(/\bhttps?:\/\/\S+/gi, "");
}

function nonEmptyLines(text) {
  return text.split(/\r?\n/).map((l) => l.trim()).filter((l) => l.length > 0);
}

// A line of emoji / box characters only, with an optional "= N" tail (and
// whatever a player typed after it, e.g. "= 13(cheated)").
function isGridOnlyLine(line) {
  return !/[A-Za-z0-9]/.test(line.replace(/=\s*\d+.*$/, ""));
}

// Collapse a Wordle-style grid to its 🟩 count per guess, plus the N/6 (or X/6)
// from the header: six rows become "🟩 2·3·4·4·4·5 6/6".
function greensSparkline(raw, headerPattern) {
  const lines = nonEmptyLines(stripUrls(raw));
  const greens = lines
    .filter((l) => isGridOnlyLine(l) && /[🟩🟨🟧🟥⬜⬛]/u.test(l))
    .map((l) => (l.match(/🟩/gu) || []).length);
  if (greens.length === 0) return null;
  const header = lines.find((l) => headerPattern.test(l));
  const fraction = header ? (header.match(/(?:\d+|X)\/\d+/i) || [])[0] : undefined;
  const sparkline = "🟩 " + greens.join("·");
  return fraction ? sparkline + " " + fraction : sparkline;
}

function format(raw) {
  return greensSparkline(raw, /tradle/i);
}
$gc$,
    "code_version" = 1
WHERE "code_version" = 0 AND "game_key" = 'tradle';
--> statement-breakpoint
-- GeoSports
UPDATE "games"
SET "parse_code" = $gc$// "1,000" → 1000. Throws rather than guessing.
function toNumber(text) {
  const digits = text.replace(/,/g, "");
  const n = Number(digits);
  if (digits === "" || !Number.isFinite(n)) throw new Error("not a number: " + text);
  return n;
}

// "711 / 1,000" → 711 (points; higher is better)
function parse(raw) {
  const m = raw.match(/([\d,]+)\s*\/\s*[\d,]+/);
  if (!m) throw new Error("no 'N / M' score");
  return toNumber(m[1]);
}
$gc$,
    "format_code" = $gc$function stripUrls(text) {
  return text.replace(/\bhttps?:\/\/\S+/gi, "");
}

function nonEmptyLines(text) {
  return text.split(/\r?\n/).map((l) => l.trim()).filter((l) => l.length > 0);
}

// A line of emoji / box characters only, with an optional "= N" tail (and
// whatever a player typed after it, e.g. "= 13(cheated)").
function isGridOnlyLine(line) {
  return !/[A-Za-z0-9]/.test(line.replace(/=\s*\d+.*$/, ""));
}

// Keep the emoji row and the "N / 1,000" line, in that order.
function format(raw) {
  const lines = nonEmptyLines(stripUrls(raw));
  const grid = lines.find(isGridOnlyLine);
  const score = lines.find((l) => /[\d,]+\s*\/\s*[\d,]+/.test(l));
  if (!grid || !score) return null;
  return grid + "\n" + score;
}
$gc$,
    "code_version" = 1
WHERE "code_version" = 0 AND "game_key" = 'geosports';
--> statement-breakpoint
-- EthnoGuessr
UPDATE "games"
SET "parse_code" = $gc$// "1,000" → 1000. Throws rather than guessing.
function toNumber(text) {
  const digits = text.replace(/,/g, "");
  const n = Number(digits);
  if (digits === "" || !Number.isFinite(n)) throw new Error("not a number: " + text);
  return n;
}

// "I scored an average of 3197 over 10 rounds …" → 3197. The later "5000
// points on round 2" is a per-round brag, not the score.
function parse(raw) {
  const m = raw.match(/average of\s*([\d,]+)/i);
  if (!m) throw new Error("no 'average of N'");
  return toNumber(m[1]);
}
$gc$,
    "format_code" = $gc$// Show just the average.
function format(raw) {
  const m = raw.match(/average of\s*([\d,]+)/i);
  return m ? m[1].replace(/,/g, "") : null;
}
$gc$,
    "code_version" = 1
WHERE "code_version" = 0 AND "game_key" IS NULL AND "normalized_url" = 'hbd.gg/play';
--> statement-breakpoint
-- Framed
UPDATE "games"
SET "parse_code" = $gc$// "🎥 🟥 🟥 🟩 ⬛ ⬛ ⬛" → 3: the guess that landed is the position of 🟩 among
// the squares. No 🟩 is a loss. (Not the puzzle number in "Framed #1234".)
function parse(raw) {
  const squares = raw.match(/🟩|🟥|⬛|⬜/gu);
  if (!squares) throw new Error("no guess squares");
  const at = squares.indexOf("🟩");
  return at === -1 ? null : at + 1;
}
$gc$,
    "format_code" = NULL,
    "code_version" = 1
WHERE "code_version" = 0 AND "game_key" = 'framed';
--> statement-breakpoint
-- Connections
UPDATE "games"
SET "parse_code" = $gc$// One line of four color squares per guess: 4 rows is perfect, each mistake
// adds one. Lower is better.
function parse(raw) {
  const rows = raw
    .split(/\r?\n/)
    .map((l) => l.trim())
    .filter((l) => /^[🟨🟩🟦🟪]{4}$/u.test(l)).length;
  if (rows === 0) throw new Error("no guess rows");
  return rows;
}
$gc$,
    "format_code" = $gc$function stripUrls(text) {
  return text.replace(/\bhttps?:\/\/\S+/gi, "");
}

function nonEmptyLines(text) {
  return text.split(/\r?\n/).map((l) => l.trim()).filter((l) => l.length > 0);
}

// Drop the "Connections" / "Puzzle #N" header lines.
function format(raw) {
  const lines = nonEmptyLines(stripUrls(raw)).filter(
    (l) => !/^Connections$/i.test(l) && !/^Puzzle\s*#?\d+$/i.test(l),
  );
  return lines.length ? lines.join("\n") : null;
}
$gc$,
    "code_version" = 1
WHERE "code_version" = 0 AND "game_key" = 'connections';
--> statement-breakpoint
-- Strands
UPDATE "games"
SET "parse_code" = $gc$// 🔵 found word, 🟡 spangram, 💡 hint used. Score = hints; 0 is perfect.
function parse(raw) {
  if (!/[💡🔵🟡]/u.test(raw)) throw new Error("no Strands grid");
  return raw.split("💡").length - 1;
}
$gc$,
    "format_code" = NULL,
    "code_version" = 1
WHERE "code_version" = 0 AND "game_key" = 'strands';
--> statement-breakpoint
-- NYT Mini
UPDATE "games"
SET "parse_code" = $gc$// "… Mini Crossword in 0:16!" → 16 seconds. Reads only m:ss / h:mm:ss, so the
// "5/20/2026" date is never mistaken for the score.
function parse(raw) {
  const m = raw.match(/(?:(\d+):)?(\d+):(\d{2})/);
  if (!m) throw new Error("no m:ss solve time");
  return Number(m[1] || 0) * 3600 + Number(m[2]) * 60 + Number(m[3]);
}
$gc$,
    "format_code" = $gc$function stripUrls(text) {
  return text.replace(/\bhttps?:\/\/\S+/gi, "");
}

// The solve time as keycap digits: "0:16" → "0️⃣:1️⃣6️⃣"
function format(raw) {
  const m = stripUrls(raw).match(/\b\d+:\d{2}\b/);
  return m ? m[0].replace(/\d/g, (d) => d + "️⃣") : null;
}
$gc$,
    "code_version" = 1
WHERE "code_version" = 0 AND "game_key" = 'nyt-mini';
--> statement-breakpoint
-- Spelling Bee
UPDATE "games"
SET "parse_code" = $gc$// "I just hit Genius on Spelling Bee." → 9: the rank's position on the ladder.
const RANKS = new Map([
  ["beginner", 1],
  ["good start", 2],
  ["moving up", 3],
  ["good", 4],
  ["solid", 5],
  ["nice", 6],
  ["great", 7],
  ["amazing", 8],
  ["genius", 9],
  ["queen bee", 10],
]);

function parse(raw) {
  const m = raw.match(/(?:hit|reached|got to|made it to)\s+([A-Za-z ]{2,20}?)\s+on/i);
  if (!m) throw new Error("no rank phrase");
  const rank = RANKS.get(m[1].trim().toLowerCase().replace(/\s+/g, " "));
  if (rank === undefined) throw new Error("unknown rank: " + m[1]);
  return rank;
}
$gc$,
    "format_code" = NULL,
    "code_version" = 1
WHERE "code_version" = 0 AND "game_key" = 'spelling-bee';
--> statement-breakpoint
-- Wordle
UPDATE "games"
SET "parse_code" = $gc$// "Wordle 1,127 3/6" → 3; "X/6" is a loss.
function parse(raw) {
  const m = raw.match(/Wordle\s+[\d,]+\s+(\d+|X)\/6/i);
  if (!m) throw new Error("no Wordle result line");
  return m[1].toUpperCase() === "X" ? null : Number(m[1]);
}
$gc$,
    "format_code" = NULL,
    "code_version" = 1
WHERE "code_version" = 0 AND "game_key" = 'wordle';
--> statement-breakpoint
INSERT INTO "game_code_revisions" ("game_id", "version", "parse_code", "format_code", "source", "note")
SELECT g."id", 1, g."parse_code", g."format_code", 'seed', 'Ported from the game registry (migration 0043).'
FROM "games" g
WHERE g."code_version" = 1
  AND NOT EXISTS (SELECT 1 FROM "game_code_revisions" r WHERE r."game_id" = g."id");
--> statement-breakpoint
-- Taught games: score_spec / summary_spec jsonb, converted to code.
UPDATE "games"
SET "parse_code" = 'var SPEC = ' || "score_spec"::text || E';\n' || $gc$// Generated from a taught score rule. SPEC (above) is the rule list; this
// reads it. First rule that yields a number wins.
var LOSS = {};

function toNumber(text) {
  var n = Number(String(text).replace(/,/g, ""));
  return isFinite(n) ? n : null;
}

function regex(pattern, flags) {
  try {
    return new RegExp(pattern, flags);
  } catch (e) {
    return null;
  }
}

function evaluate(rule, raw) {
  var re, m;
  if (rule.kind === "capture") {
    re = regex(rule.pattern, "i");
    m = re && raw.match(re);
    if (!m) return null;
    return toNumber(m[1] === undefined || m[1] === null ? m[0] : m[1]);
  }
  if (rule.kind === "count") {
    if (rule.within !== undefined && rule.within !== null) {
      re = regex(rule.within, "u");
      if (!re || !re.test(raw)) return null;
    }
    return rule.token.length === 0 ? 0 : raw.split(rule.token).length - 1;
  }
  if (rule.kind === "countLines") {
    re = regex(rule.pattern, "u");
    if (!re) return null;
    var lines = raw.split(/\r?\n/).filter(function (l) { return re.test(l.trim()); }).length;
    return lines > 0 ? lines : null;
  }
  if (rule.kind === "duration") {
    re = regex(rule.pattern || "(?:(\\d+):)?(\\d+):(\\d{2})", "");
    m = re && raw.match(re);
    if (!m) return null;
    var parts = m.slice(1).filter(function (g) { return g !== undefined; }).map(Number);
    if (parts.length < 2 || parts.some(function (n) { return !isFinite(n); })) return null;
    parts.reverse();
    return (parts[0] || 0) + (parts[1] || 0) * 60 + (parts[2] || 0) * 3600;
  }
  if (rule.kind === "tokenPosition") {
    var tokens = [rule.token].concat(rule.among).filter(function (t) { return t.length > 0; });
    var position = 0;
    var cursor = 0;
    while (cursor < raw.length) {
      var earliest = -1;
      var found = "";
      for (var i = 0; i < tokens.length; i++) {
        var at = raw.indexOf(tokens[i], cursor);
        if (at !== -1 && (earliest === -1 || at < earliest)) {
          earliest = at;
          found = tokens[i];
        }
      }
      if (earliest === -1) break;
      position += 1;
      if (found === rule.token) return position;
      cursor = earliest + found.length;
    }
    // Squares but no winning one: a loss, not an unreadable share.
    return position > 0 ? LOSS : null;
  }
  if (rule.kind === "wordMap") {
    re = regex(rule.pattern, "i");
    m = re && raw.match(re);
    if (!m || !m[1]) return null;
    var wanted = m[1].trim().toLowerCase().replace(/\s+/g, " ");
    var keys = Object.keys(rule.map);
    for (var k = 0; k < keys.length; k++) {
      if (keys[k].trim().toLowerCase().replace(/\s+/g, " ") === wanted) return rule.map[keys[k]];
    }
    return null;
  }
  return null;
}

function parse(raw) {
  var lost = false;
  for (var i = 0; i < SPEC.rules.length; i++) {
    var value = evaluate(SPEC.rules[i], raw);
    if (typeof value === "number") return value;
    if (value === LOSS) lost = true;
  }
  if (lost) return null;
  throw new Error("no rule matched this share");
}
$gc$,
    "format_code" = CASE
      WHEN "summary_spec" IS NULL THEN NULL
      ELSE 'var SPEC = ' || "summary_spec"::text || E';\n' || $gc$// Generated from a taught recap rule. SPEC (above) lists the line patterns to
// keep. URLs, blank lines and hashtag-only lines are dropped first; a share
// with no matching line shows the cleaned raw text instead.
function format(raw) {
  var regexes = [];
  for (var i = 0; i < SPEC.rules.length; i++) {
    try {
      regexes.push(new RegExp(SPEC.rules[i].pattern, "u"));
    } catch (e) {}
  }
  if (regexes.length === 0) return null;
  var kept = raw
    .split(/\r?\n/)
    .map(function (l) { return l.replace(/\bhttps?:\/\/\S+/gi, "").trimEnd(); })
    .filter(function (l) { return l.trim().length > 0 && !/^\s*#\S+\s*$/.test(l); })
    .filter(function (l) { return regexes.some(function (re) { return re.test(l.trim()); }); });
  return kept.length > 0 ? kept.join("\n") : null;
}
$gc$
    END,
    "code_version" = 1
WHERE "code_version" = 0 AND "score_spec" IS NOT NULL;
--> statement-breakpoint
INSERT INTO "game_code_revisions" ("game_id", "version", "parse_code", "format_code", "source", "note")
SELECT g."id", 1, g."parse_code", g."format_code", 'spec', 'Converted from the taught score/summary spec (migration 0043).'
FROM "games" g
WHERE g."code_version" = 1
  AND NOT EXISTS (SELECT 1 FROM "game_code_revisions" r WHERE r."game_id" = g."id");
