// Builds the SQL of the seed migration (drizzle/0043_seed_game_code.sql) from
// the code in builtin.ts and specCode.ts. The migration file is this
// function's output, committed; `seed.test.ts` fails if the two differ, and
// `scripts/generate-game-code-seed.ts` rewrites the file.
//
// A migration that has shipped is history. To change a game's code after
// that, use the admin script (or write a NEW migration) — do not regenerate
// this one.

import { normalizeGameUrl } from "@workshop/shared/games";
import { BUILTIN_GAMES } from "./builtin.js";
import { SCORE_SPEC_INTERPRETER, SPEC_CODE_PREFIX, SUMMARY_SPEC_INTERPRETER } from "./specCode.js";

const QUOTE = "$gc$";
const BREAK = "\n--> statement-breakpoint\n";

function sqlText(value: string | null): string {
  if (value === null) return "NULL";
  if (value.includes(QUOTE)) throw new Error(`game code contains the SQL quote tag ${QUOTE}`);
  return `${QUOTE}${value}${QUOTE}`;
}

function sqlLiteral(value: string): string {
  return `'${value.replace(/'/g, "''")}'`;
}

function recordRevisions(source: string, note: string): string {
  return `INSERT INTO "game_code_revisions" ("game_id", "version", "parse_code", "format_code", "source", "note")
SELECT g."id", 1, g."parse_code", g."format_code", ${sqlLiteral(source)}, ${sqlLiteral(note)}
FROM "games" g
WHERE g."code_version" = 1
  AND NOT EXISTS (SELECT 1 FROM "game_code_revisions" r WHERE r."game_id" = g."id");`;
}

/**
 * Convert every taught `score_spec` / `summary_spec` that has no code yet:
 * the stored spec, as data, in front of the interpreter — the text
 * compileScoreSpec / compileSummarySpec produce.
 */
function taughtSpecStatements(origin: string): string[] {
  const prefix = sqlLiteral(SPEC_CODE_PREFIX);
  return [
    `-- Taught games: score_spec / summary_spec jsonb, converted to code.
UPDATE "games"
SET "parse_code" = ${prefix} || "score_spec"::text || E';\\n' || ${sqlText(SCORE_SPEC_INTERPRETER)},
    "format_code" = CASE
      WHEN "summary_spec" IS NULL THEN NULL
      ELSE ${prefix} || "summary_spec"::text || E';\\n' || ${sqlText(SUMMARY_SPEC_INTERPRETER)}
    END,
    "code_version" = 1
WHERE "code_version" = 0 AND "score_spec" IS NOT NULL;`,
    recordRevisions("spec", `Converted from the taught score/summary spec (${origin}).`),
  ];
}

/**
 * drizzle/0044: the taught-spec conversion again. `PUT /v1/games/:id/score-spec`
 * only started writing code alongside the spec in the release that carries
 * this migration, so a game taught between 0043 and that release has a spec
 * and no code. Idempotent, and a no-op when there is no such game.
 */
export function buildTaughtSpecCatchUpSql(): string {
  const header = `-- GENERATED by scripts/generate-game-code-seed.ts from src/lib/gameCode/specCode.ts.
-- Do not edit by hand: seed.test.ts compares this file to the generator's output.
--
-- Converts any score spec taught after migration 0043 ran and before the
-- teach endpoint began writing code itself. Idempotent; usually a no-op.
`;
  return `${header}${taughtSpecStatements("migration 0044").join(BREAK)}\n`;
}

export function buildGameCodeSeedSql(): string {
  const statements: string[] = [];

  // 1. Registry games: the hand-ported code. `code_version = 0` makes every
  //    statement a no-op on a row that already has code, so re-running the
  //    file changes nothing and never overwrites an operator's edit.
  for (const { def, code } of BUILTIN_GAMES) {
    // Catalog games are seeded rows keyed by game_key. A detection-only game
    // (EthnoGuessr) has no seeded row; if a player already added it, the row
    // is found by its URL.
    const match = def.catalog
      ? `"game_key" = ${sqlLiteral(def.key)}`
      : `"game_key" IS NULL AND "normalized_url" = ${sqlLiteral(normalizeGameUrl(def.canonicalUrl) ?? "")}`;
    statements.push(
      `-- ${def.title}
UPDATE "games"
SET "parse_code" = ${sqlText(code.parse)},
    "format_code" = ${sqlText(code.format)},
    "code_version" = 1
WHERE "code_version" = 0 AND ${match};`,
    );
  }
  statements.push(recordRevisions("seed", "Ported from the game registry (migration 0043)."));

  // 2. Games taught through the tap-the-score flow.
  statements.push(...taughtSpecStatements("migration 0043"));

  const header = `-- GENERATED by scripts/generate-game-code-seed.ts from src/lib/gameCode/builtin.ts
-- and specCode.ts. Do not edit by hand: seed.test.ts compares this file to the
-- generator's output.
--
-- Installs each game's parse / format code (the JavaScript the QuickJS sandbox
-- runs — see src/lib/gameCode/README.md) and records it as version 1 in
-- game_code_revisions. Idempotent: every statement skips rows that already
-- have code. Nothing reads these columns until GAME_CODE_PARSING is on.
`;
  return `${header}${statements.join(BREAK)}\n`;
}
